// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	time "time"
)

type DailyGross struct {
	ID    string    `json:"id"`
	Date  time.Time `json:"Date"`
	Gross *int      `json:"Gross"`
}

type Film struct {
	ID         string       `json:"id"`
	BomID      *string      `json:"bomID"`
	Title      *string      `json:"title"`
	GrossDaily []DailyGross `json:"grossDaily"`
}
